# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Downstage < Formula
  desc "Plaintext markup language and tools for stage plays"
  homepage "https://github.com/jscaltreto/downstage"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jscaltreto/downstage/releases/download/v0.1.0/downstage_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "16026ac2b905189d695dcc377a129560ae36f88dbf2b2afcaf6d1b31633a565a"

      define_method(:install) do
        bin.install "downstage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jscaltreto/downstage/releases/download/v0.1.0/downstage_0.1.0_Darwin_arm64.tar.gz"
      sha256 "4352d68990d29df9acf19ca074ebe0b9886c01bdfede660cb831106445c5ded1"

      define_method(:install) do
        bin.install "downstage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jscaltreto/downstage/releases/download/v0.1.0/downstage_0.1.0_Linux_x86_64.tar.gz"
      sha256 "5e75d2a0a0c67d16787e402ed485b8e73e7ff5e8a7e098d7fc6721d164362648"
      define_method(:install) do
        bin.install "downstage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jscaltreto/downstage/releases/download/v0.1.0/downstage_0.1.0_Linux_arm64.tar.gz"
      sha256 "586cd2523f3fa1a920c462676b3d2906866f27b4df6c03d60e14ff26205da660"
      define_method(:install) do
        bin.install "downstage"
      end
    end
  end

  test do
    system "#{bin}/downstage", "version"
  end
end
